[package]
name = "trpg-ability"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
uuid.workspace = true
tracing.workspace = true
trpg-db = { path = "../trpg-db" }
trpg-model = { path = "../trpg-model" }
trpg-search = { path = "../trpg-search" }
trpg-semantics = { path = "../trpg-semantics" }
