//! 上下文块类型枚举（`BlockKind`）。
//!
//! 从 `lib.rs` facade 拆出的低耦合定义簇。通过 `pub use block::*` 在 crate 根
//! 重导出，serde 名称、derive、变体与公共 API 保持不变。

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum BlockKind {
    EngineProtocol,
    OutputSchema,
    ToolProtocol,
    RulesetResidentCore,
    RulesetWorldStyle,
    RulesetDirectorPolicy,
    RulesetActionRouter,
    RulesetIndex,
    RulesetCharacterKernel,
    RulesetOnboarding,
    RuleStewardKernel,
    MechanicsCatalogIndex,
    RuleAgentRun,
    RuleKernelPatch,
    RuleEntityLocator,
    MechanicalSourcePack,
    PlayabilityGateReport,
    CharacterOnboardingPack,
    CharacterCreationFlow,
    CharacterOptionCatalog,
    DerivedFormulaPack,
    StarterCharacterPack,
    GameIdentity,
    PlayLoop,
    BookLocator,
    LookupRecipe,
    GmOnboarding,
    BookLocatorSummary,
    ColdDataLocator,
    LearnedPacket,
    LookupResult,
    Ruling,
    RulingLog,
    RulePackage,
    ProcedureDetail,
    ProcedureVariant,
    ParameterFamily,
    ParameterEntry,
    DomainActor,
    DomainObject,
    ObjectDefinition,
    ObjectInstance,
    ObjectAffordance,
    ObjectInteractionContract,
    ObjectPatch,
    ObjectEvent,
    ObjectGraph,
    DomainAbility,
    AbilityDefinition,
    AbilityInstance,
    AbilityTriggerBinding,
    AbilityActivationContract,
    AbilityGraph,
    RuleBindingPacket,
    SemanticClassification,
    MaterializationDemand,
    SourceEvidenceBundle,
    ExtractionRun,
    BindingVerification,
    ActorRuntimeBinding,
    ObjectRuntimeBinding,
    AbilityRuntimeBinding,
    MaterializationGraph,
    PlayerValueClaim,
    PlayerValueVerification,
    TableOverrideAgreement,
    RefereeRuling,
    MechanicalLedger,
    AttackResolutionContract,
    DamagePacket,
    RollPlan,
    EffectResolutionPacket,
    ParameterImpact,
    ActorMechanicalState,
    CombatRoundAction,
    CombatRoundTransition,
    ContestProfile,
    OppositionProfile,
    ContestResolution,
    ContestGraph,
    MechanicsSearchSkill,
    MechanicsQueryPlan,
    ParameterFacetBinding,
    MechanicsSearchTrace,
    MechanicsSearchGraph,
    ParameterFacetExecution,
    GenericParameterState,
    RulesetMechanicalProfile,
    DomainInfo,
    DomainPlace,
    DomainScenario,
    StateTrait,
    StateTrack,
    StateStatus,
    StateAspect,
    StateModifier,
    ScenarioNode,
    MissionStatic,
    Clue,
    Handout,
    NpcStatic,
    LocationStatic,
    ChapterStatic,
    ModuleSpine,
    ModuleStyle,
    ModuleSpecificRule,
    ModuleOverview,
    CurrentSessionPacket,
    SessionSummary,
    MemorySnapshot,
    MemoryFact,
    MemoryEvent,
    SceneStatic,
    AgentPlan,
    AgentAdvice,
    CheckContract,
    PendingCheck,
    InteractionGate,
    DiceRoll,
    StateFrame,
    FrameEvent,
    FrameCompaction,
    CombatFrame,
    CombatEvent,
    EffectContract,
    CombatProfile,
    ReactionWindow,
    DirectorPolicy,
    ActionableSituationBrief,
    ClueBoard,
    ConsequenceContract,
    SpotlightState,
    ClockEvent,
    WorldTime,
    WorldEvent,
    TimeAdvance,
    ScheduledEvent,
    TimeAnchor,
    WorldState,
    RetrievedMemory,
    RecentTranscript,
    CurrentInput,
}

impl BlockKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            BlockKind::EngineProtocol => "engine_protocol",
            BlockKind::OutputSchema => "output_schema",
            BlockKind::ToolProtocol => "tool_protocol",
            BlockKind::RulesetResidentCore => "ruleset_resident_core",
            BlockKind::RulesetWorldStyle => "ruleset_world_style",
            BlockKind::RulesetDirectorPolicy => "ruleset_director_policy",
            BlockKind::RulesetActionRouter => "ruleset_action_router",
            BlockKind::RulesetIndex => "ruleset_index",
            BlockKind::RulesetCharacterKernel => "ruleset_character_kernel",
            BlockKind::RulesetOnboarding => "ruleset_onboarding",
            BlockKind::RuleStewardKernel => "rule_steward_kernel",
            BlockKind::MechanicsCatalogIndex => "mechanics_catalog_index",
            BlockKind::RuleAgentRun => "rule_agent_run",
            BlockKind::RuleKernelPatch => "rule_kernel_patch",
            BlockKind::RuleEntityLocator => "rule_entity_locator",
            BlockKind::MechanicalSourcePack => "mechanical_source_pack",
            BlockKind::PlayabilityGateReport => "playability_gate_report",
            BlockKind::CharacterOnboardingPack => "character_onboarding_pack",
            BlockKind::CharacterCreationFlow => "character_creation_flow",
            BlockKind::CharacterOptionCatalog => "character_option_catalog",
            BlockKind::DerivedFormulaPack => "derived_formula_pack",
            BlockKind::StarterCharacterPack => "starter_character_pack",
            BlockKind::GameIdentity => "game_identity",
            BlockKind::PlayLoop => "play_loop",
            BlockKind::BookLocator => "book_locator",
            BlockKind::LookupRecipe => "lookup_recipe",
            BlockKind::GmOnboarding => "gm_onboarding",
            BlockKind::BookLocatorSummary => "book_locator_summary",
            BlockKind::ColdDataLocator => "cold_data_locator",
            BlockKind::LearnedPacket => "learned_packet",
            BlockKind::LookupResult => "lookup_result",
            BlockKind::Ruling => "ruling",
            BlockKind::RulingLog => "ruling_log",
            BlockKind::RulePackage => "rule_package",
            BlockKind::ProcedureDetail => "procedure_detail",
            BlockKind::ProcedureVariant => "procedure_variant",
            BlockKind::ParameterFamily => "parameter_family",
            BlockKind::ParameterEntry => "parameter_entry",
            BlockKind::DomainActor => "domain_actor",
            BlockKind::DomainObject => "domain_object",
            BlockKind::ObjectDefinition => "object_definition",
            BlockKind::ObjectInstance => "object_instance",
            BlockKind::ObjectAffordance => "object_affordance",
            BlockKind::ObjectInteractionContract => "object_interaction_contract",
            BlockKind::ObjectPatch => "object_patch",
            BlockKind::ObjectEvent => "object_event",
            BlockKind::ObjectGraph => "object_graph",
            BlockKind::DomainAbility => "domain_ability",
            BlockKind::AbilityDefinition => "ability_definition",
            BlockKind::AbilityInstance => "ability_instance",
            BlockKind::AbilityTriggerBinding => "ability_trigger_binding",
            BlockKind::AbilityActivationContract => "ability_activation_contract",
            BlockKind::AbilityGraph => "ability_graph",
            BlockKind::RuleBindingPacket => "rule_binding_packet",
            BlockKind::SemanticClassification => "semantic_classification",
            BlockKind::MaterializationDemand => "materialization_demand",
            BlockKind::SourceEvidenceBundle => "source_evidence_bundle",
            BlockKind::ExtractionRun => "extraction_run",
            BlockKind::BindingVerification => "binding_verification",
            BlockKind::ActorRuntimeBinding => "actor_runtime_binding",
            BlockKind::ObjectRuntimeBinding => "object_runtime_binding",
            BlockKind::AbilityRuntimeBinding => "ability_runtime_binding",
            BlockKind::MaterializationGraph => "materialization_graph",
            BlockKind::PlayerValueClaim => "player_value_claim",
            BlockKind::PlayerValueVerification => "player_value_verification",
            BlockKind::TableOverrideAgreement => "table_override_agreement",
            BlockKind::RefereeRuling => "referee_ruling",
            BlockKind::MechanicalLedger => "mechanical_ledger",
            BlockKind::AttackResolutionContract => "attack_resolution_contract",
            BlockKind::DamagePacket => "damage_packet",
            BlockKind::RollPlan => "roll_plan",
            BlockKind::EffectResolutionPacket => "effect_resolution_packet",
            BlockKind::ParameterImpact => "parameter_impact",
            BlockKind::ActorMechanicalState => "actor_mechanical_state",
            BlockKind::CombatRoundAction => "combat_round_action",
            BlockKind::CombatRoundTransition => "combat_round_transition",
            BlockKind::ContestProfile => "contest_profile",
            BlockKind::OppositionProfile => "opposition_profile",
            BlockKind::ContestResolution => "contest_resolution",
            BlockKind::ContestGraph => "contest_graph",
            BlockKind::MechanicsSearchSkill => "mechanics_search_skill",
            BlockKind::MechanicsQueryPlan => "mechanics_query_plan",
            BlockKind::ParameterFacetBinding => "parameter_facet_binding",
            BlockKind::MechanicsSearchTrace => "mechanics_search_trace",
            BlockKind::MechanicsSearchGraph => "mechanics_search_graph",
            BlockKind::ParameterFacetExecution => "parameter_facet_execution",
            BlockKind::GenericParameterState => "generic_parameter_state",
            BlockKind::RulesetMechanicalProfile => "ruleset_mechanical_profile",
            BlockKind::DomainInfo => "domain_info",
            BlockKind::DomainPlace => "domain_place",
            BlockKind::DomainScenario => "domain_scenario",
            BlockKind::StateTrait => "state_trait",
            BlockKind::StateTrack => "state_track",
            BlockKind::StateStatus => "state_status",
            BlockKind::StateAspect => "state_aspect",
            BlockKind::StateModifier => "state_modifier",
            BlockKind::ScenarioNode => "scenario_node",
            BlockKind::MissionStatic => "mission_static",
            BlockKind::Clue => "clue",
            BlockKind::Handout => "handout",
            BlockKind::NpcStatic => "npc_static",
            BlockKind::LocationStatic => "location_static",
            BlockKind::ChapterStatic => "chapter_static",
            BlockKind::ModuleSpine => "module_spine",
            BlockKind::ModuleStyle => "module_style",
            BlockKind::ModuleSpecificRule => "module_specific_rule",
            BlockKind::ModuleOverview => "module_overview",
            BlockKind::CurrentSessionPacket => "current_session_packet",
            BlockKind::SessionSummary => "session_summary",
            BlockKind::MemorySnapshot => "memory_snapshot",
            BlockKind::MemoryFact => "memory_fact",
            BlockKind::MemoryEvent => "memory_event",
            BlockKind::SceneStatic => "scene_static",
            BlockKind::AgentPlan => "agent_plan",
            BlockKind::AgentAdvice => "agent_advice",
            BlockKind::CheckContract => "check_contract",
            BlockKind::PendingCheck => "pending_check",
            BlockKind::InteractionGate => "interaction_gate",
            BlockKind::DiceRoll => "dice_roll",
            BlockKind::StateFrame => "state_frame",
            BlockKind::FrameEvent => "frame_event",
            BlockKind::FrameCompaction => "frame_compaction",
            BlockKind::CombatFrame => "combat_frame",
            BlockKind::CombatEvent => "combat_event",
            BlockKind::EffectContract => "effect_contract",
            BlockKind::CombatProfile => "combat_profile",
            BlockKind::ReactionWindow => "reaction_window",
            BlockKind::DirectorPolicy => "director_policy",
            BlockKind::ActionableSituationBrief => "actionable_situation_brief",
            BlockKind::ClueBoard => "clue_board",
            BlockKind::ConsequenceContract => "consequence_contract",
            BlockKind::SpotlightState => "spotlight_state",
            BlockKind::ClockEvent => "clock_event",
            BlockKind::WorldTime => "world_time",
            BlockKind::WorldEvent => "world_event",
            BlockKind::TimeAdvance => "time_advance",
            BlockKind::ScheduledEvent => "scheduled_event",
            BlockKind::TimeAnchor => "time_anchor",
            BlockKind::WorldState => "world_state",
            BlockKind::RetrievedMemory => "retrieved_memory",
            BlockKind::RecentTranscript => "recent_transcript",
            BlockKind::CurrentInput => "current_input",
        }
    }
}
