[package]
name = "trpg-params"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
trpg-db = { path = "../trpg-db" }
trpg-model = { path = "../trpg-model" }
sqlx.workspace = true
